# -*- coding: utf-8 -*-
"""drift.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfDRhWyuLMxVFsDyu7WjSNZNkQn3uAgW
"""

!pip install copernicusmarine fastapi uvicorn scipy xarray

!pip install copernicusmarine fastapi uvicorn scipy xarray

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from scipy.interpolate import RegularGridInterpolator

# Step 1: Load your dataset
# Replace 'your_dataset.csv' with the actual filename
# Fix: Create a dummy CSV file if it doesn't exist for demonstration
try:
    df = pd.read_csv("your_dataset.csv")
except FileNotFoundError:
    print("your_dataset.csv not found. Creating a dummy dataset for demonstration.")
    data = {
        'decimalLatitude': [20.0, 20.0, 20.0, 20.2, 20.2, 20.2, 20.4, 20.4, 20.4],
        'decimalLongitude': [86.5, 86.7, 86.9, 86.5, 86.7, 86.9, 86.5, 86.7, 86.9],
        'current_speed': [0.1, 0.2, 0.15, 0.25, 0.3, 0.2, 0.1, 0.18, 0.12]
    }
    df = pd.DataFrame(data)
    # Optionally save it for future runs
    df.to_csv("your_dataset.csv", index=False)


# Inspect columns
print("Columns in dataset:", df.columns)

# Step 2: Build interpolators for current speed
# Assume current_speed is scalar magnitude, we need eastward/northward components.
# For simplicity, we treat current_speed as eastward (u) and northward (v) equally split.
# In real physics, you'd need direction data, but here we approximate.

lats = df['decimalLatitude'].unique()
lons = df['decimalLongitude'].unique()

# Pivot to grid form
u_grid = df.pivot_table(index='decimalLatitude', columns='decimalLongitude', values='current_speed').values
v_grid = df.pivot_table(index='decimalLatitude', columns='decimalLongitude', values='current_speed').values

interp_u = RegularGridInterpolator((lats, lons), u_grid, bounds_error=False, fill_value=0)
interp_v = RegularGridInterpolator((lats, lons), v_grid, bounds_error=False, fill_value=0)

# Step 3: Backward drift function
def run_backward_drift(stranding_lat, stranding_lon, hours=72, dt_hours=6):
    """
    Run a backward drift simulation using current_speed from dataset.
    """
    dt_seconds = dt_hours * 3600
    steps = hours // dt_hours

    path = [(stranding_lat, stranding_lon)]
    cur_lat, cur_lon = stranding_lat, stranding_lon

    for _ in range(steps):
        pt = np.array([[cur_lat, cur_lon]])
        # Fix: Use .item() to explicitly extract the scalar value from the NumPy array
        u_at_pt = interp_u(pt).item()
        v_at_pt = interp_v(pt).item()

        # Move BACKWARD: subtract velocity × time
        delta_lat = -(v_at_pt * dt_seconds) / 111_000
        delta_lon = -(u_at_pt * dt_seconds) / (111_000 * np.cos(np.radians(cur_lat)))

        cur_lat += delta_lat
        cur_lon += delta_lon
        path.append((round(cur_lat, 4), round(cur_lon, 4)))

    return path

# Step 4: Test with example coordinates
lat, lon = 20.2, 86.7   # Odisha coast example
path = run_backward_drift(lat, lon)

print("Drift path:", path)
print("Estimated origin after 72h:", path[-1])

import matplotlib.pyplot as plt

# Convert np.float64 values to plain floats for plotting
clean_path = [(float(lat), float(lon)) for lat, lon in path]

# Separate latitudes and longitudes
lats = [p[0] for p in clean_path]
lons = [p[1] for p in clean_path]

# Plot drift path
plt.figure(figsize=(8,6))
plt.plot(lons, lats, marker='o', linestyle='-', color='blue', label='Drift Path')

# Highlight start and end points
plt.scatter(lons[0], lats[0], color='green', s=100, label='Stranding Point')
plt.scatter(lons[-1], lats[-1], color='red', s=100, label='Estimated Origin')

# Labels and title
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Backward Drift Path")
plt.legend()
plt.grid(True)
plt.show()