# -*- coding: utf-8 -*-
"""drift_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTxvxRVtw0hwBJFvIhaTLFaFnHt82JXl
"""

# drift.py

import numpy as np
from scipy.interpolate import RegularGridInterpolator

# --- Core Functions ---

def build_interpolators(df):
    """
    Build interpolators for current_speed from your dataset.
    Returns interp_u, interp_v.
    """
    lats = df['decimalLatitude'].unique()
    lons = df['decimalLongitude'].unique()

    u_grid = df.pivot_table(index='decimalLatitude',
                            columns='decimalLongitude',
                            values='current_speed').values
    v_grid = df.pivot_table(index='decimalLatitude',
                            columns='decimalLongitude',
                            values='current_speed').values

    interp_u = RegularGridInterpolator((lats, lons), u_grid,
                                       bounds_error=False, fill_value=0)
    interp_v = RegularGridInterpolator((lats, lons), v_grid,
                                       bounds_error=False, fill_value=0)

    return interp_u, interp_v


def run_backward_drift(stranding_lat, stranding_lon, interp_u, interp_v,
                       hours=72, dt_hours=6):
    """
    Run a backward drift simulation using current_speed.
    """
    dt_seconds = dt_hours * 3600
    steps = hours // dt_hours

    path = [(stranding_lat, stranding_lon)]
    cur_lat, cur_lon = stranding_lat, stranding_lon

    for _ in range(steps):
        pt = np.array([[cur_lat, cur_lon]])
        u_at_pt = interp_u(pt).item()
        v_at_pt = interp_v(pt).item()

        delta_lat = -(v_at_pt * dt_seconds) / 111_000
        delta_lon = -(u_at_pt * dt_seconds) / (111_000 * np.cos(np.radians(cur_lat)))

        cur_lat += delta_lat
        cur_lon += delta_lon
        path.append((round(cur_lat, 4), round(cur_lon, 4)))

    return path