# -*- coding: utf-8 -*-
"""test_drift.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOk3m44yoDT4txiNmQzVu2mB6SkS36qs
"""

# test_drift.py

import pandas as pd
from drift_clean import build_interpolators, run_backward_drift

# Load dataset
df = pd.read_csv("your_dataset.csv")

# Build interpolators
interp_u, interp_v = build_interpolators(df)

# Run drift
lat, lon = 20.2, 86.7
path = run_backward_drift(lat, lon, interp_u, interp_v)

print("Path:", path)
print("Origin:", path[-1])